In [4]:
import numpy as np
a = np.array([[2,4,6],[1,3,5],[6,8,7]])
b = np.array([[3,2,1],[6,5,4],[7,6,8]])
print("Matrix A:\n", a)
print("Matrix B:\n", b)
sum = a+b
print("Matrix Addition:\n", sum)
substract=a-b
("Matrix Subtraction:\n", substract)
multiply=a*b
print("Element-wise Multiplication:\n", multiply)
matrix_maltiplication = np.dot(a,b)
print("Matrix Multiplication (Dot Product):\n", matrix_maltiplication)

Matrix A:
 [[2 4 6]
 [1 3 5]
 [6 8 7]]
Matrix B:
 [[3 2 1]
 [6 5 4]
 [7 6 8]]
Matrix Addition:
 [[ 5  6  7]
 [ 7  8  9]
 [13 14 15]]
Element-wise Multiplication:
 [[ 6  8  6]
 [ 6 15 20]
 [42 48 56]]
Matrix Multiplication (Dot Product):
 [[ 72  60  66]
 [ 56  47  53]
 [115  94  94]]


In [10]:
a1 = np.array([[2,4,6],[1,3,5]])
b1 = np.array([[3,2],[6,5],[7,6]])
print("Matrix A:\n", a1)
print("Matrix B:\n", b1)
# sum1 = a1+b1
# print("Matrix Addition:\n", sum1)
# substract1=a1-b1
# ("Matrix Subtraction:\n", substract1)
# multiply1=a1*b1
# print("Element-wise Multiplication:\n", multiply1)
matrix_maltiplication1 = np.dot(a1,b1)
print("Matrix Multiplication (Dot Product):\n", matrix_maltiplication1)

Matrix A:
 [[2 4 6]
 [1 3 5]]
Matrix B:
 [[3 2]
 [6 5]
 [7 6]]
Matrix Multiplication (Dot Product):
 [[72 60]
 [56 47]]


In [24]:
# Practice Questions
# Solve this system:
# 4x + 2y = 14
# x + y = 5
# Try changing the constants in the original system and solve again.
# What happens if the matrix is not invertible? Try this:
A = np.array([[1, 2], [2, 4]])
B = np.array([5, 10])
# Use np.linalg.solve() — does it work?


a3=np.array([[4,2],[1,1]])
b3 = np.array([14,5])
solution = np.linalg.solve(a3,b3)
print("Solution of matrix:\n", solution)

solution2 = np.linalg.solve(A,B)
print("Solution of matrix:\n", solution2)

Solution of matrix:
 [2. 3.]


LinAlgError: Singular matrix

In [25]:
# Q1. Stock Portfolio Return
# You invested in 3 different stocks over 4 days. The matrix below shows returns of each stock over time.
# Create a 1x3 weight vector for investment percentages and calculate the total daily return using matrix multiplication.
Returns = np.array([[0.01, 0.02, 0.015],
           [0.012, 0.018, 0.017],
           [0.011, 0.019, 0.014],
           [0.013, 0.021, 0.016]])
Weights = np.array([0.4, 0.3, 0.3])
total_daily = np.dot(Returns,Weights)
print("Daily Return of market is: ",total_daily)

Daily Return of market is:  [0.0145 0.0153 0.0143 0.0163]


In [26]:
# Q2. Image Brightness Adjustment
# An image is represented as a 3x3 matrix. Increase brightness by adding a scalar value of 50 to every pixel.

Image = np.array([[120, 150, 200],
         [100, 180, 160],
         [130, 140, 170]])
increased_brightness = Image * 50
print("Increase brightness is: ",increased_brightness)

Increase brightness is:  [[ 6000  7500 10000]
 [ 5000  9000  8000]
 [ 6500  7000  8500]]


In [46]:
# Q3. Rotate a Matrix 90 Degrees
# Given a matrix:

A_Matrix= np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])
rotate_matrix = np.rot90(A_Matrix)
print("rotate_matrix is: ",rotate_matrix)

rotate_matrix is:  [[3 6 9]
 [2 5 8]
 [1 4 7]]


In [29]:
# Q4. Matrix Dot Product for Recommendation Score
# User preference vector and product feature matrix:
# Compute recommendation score for each product using dot product.
User = np.array([0.2, 0.8])
Products = np.array([[0.9, 0.1],
            [0.3, 0.7],
            [0.5, 0.5]])
Compute_recommendation_score = np.dot(Products,User)
print("Compute_recommendation_score is: ",Compute_recommendation_score)

Compute_recommendation_score is:  [0.26 0.62 0.5 ]


In [30]:
# Q5. Traffic Flow Estimation
# Solve for traffic at 2 intersections:
# 3x + 2y = 390
# 2x + 3y = 360
# Use NumPy to find the number of cars x and y going through each road.
traffic1 = np.array([[3,2],[2,3]])
traffic2 = np.array([390,360])
number_cars = np.linalg.solve(traffic1,traffic2)
print("number_cars is: ",number_cars)

number_cars is:  [90. 60.]


In [44]:
# Q6. Transpose Comparison
# Create a random 4x3 matrix. Print its transpose and verify that element at (1, 2) in original becomes (2, 1) in transpose.
# Use NumPy random and slicing to verify it.
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
transpose_matrix = np.transpose(mat1)
print(mat1,"transpose_matrix is: ",transpose_matrix)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] transpose_matrix is:  [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [42]:
# Q7. Identity Matrix Verification
# Create a random 3x3 matrix M. Multiply it with identity matrix I. Confirm that the result is same as M.
# Also verify that I * M equals M as well.
mat2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
I = np.identity(3)
print(I)
multi =np.dot(mat2,I)
print("Identity Matrix Verification is: ",multi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity Matrix Verification is:  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [40]:
# Q8. Daily Sales Tracking
# A store tracks sales of 4 items over 5 days:
# Find:
# Total units sold per item (column-wise sum)
# Average sales per day (row-wise mean)
Sales =np.array([[10, 12, 15, 20],
         [11, 9, 14, 19],
         [13, 10, 16, 18],
         [12, 11, 15, 21],
         [14, 13, 17, 22]])
# Total units sold per item (sum of each column)
total_per_item = np.sum(Sales, axis=0)

# Average sales per day (mean of each row)
average_per_day = np.mean(Sales, axis=1)

# Output the results
print("Total units sold per item:", total_per_item)
print("Average sales per day:", average_per_day)

Total units sold per item: [ 60  55  77 100]
Average sales per day: [14.25 13.25 14.25 14.75 16.5 ]


In [39]:
# Q9. Matrix Inversion Check
# Create a 2x2 matrix:
# Use NumPy to compute inverse A_inv and verify that A dot A_inv gives identity matrix.
Amat = np.array([[4, 7],
     [2, 6]])
A_inv = np.linalg.inv(Amat)
print(A_inv)
a_dot = np.dot(Amat,A_inv)
print(a_dot)

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


In [48]:
# Q10. Error Handling: Singular Matrix
# Try solving this system:
# Use np.linalg.solve() and handle the error if matrix is singular (non-invertible). Print a message instead of crashing the code.
A1 = np.array([[2, 4],
     [1, 2]])
B1 = np.array([10, 5])

try:
    # Attempt to solve Ax = b
    x = np.linalg.solve(A1, B1)
    print("Solution x:", x)
except np.linalg.LinAlgError as e:
    print("Error:", e)
    print("The matrix is singular and cannot be solved.")



Error: Singular matrix
The matrix is singular and cannot be solved.
